// Manual sidebar — the locked six-section structure.
// Existing multi-page chapters use `autogenerated`; task chapters and dropdowns
// are explicit. Files are not moved, so existing URLs are unchanged.

/** A collapsible chapter that pulls in all pages of an existing folder. */
const chapter = (label, dirName) => ({
  type: 'category',
  label,
  collapsed: true,
  items: [{ type: 'autogenerated', dirName }],
});

/** A chapter with a landing page (the index) plus explicit child pages. */
const chapterIndexed = (label, indexId, items) => ({
  type: 'category',
  label,
  collapsed: true,
  link: { type: 'doc', id: indexId },
  items,
});

/** A section: a top-level group with an Overview landing page. */
const section = (label, overviewId, items, collapsed = true) => ({
  type: 'category',
  label,
  collapsed,
  link: { type: 'doc', id: overviewId },
  items,
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      link: { type: 'doc', id: 'introduction/index' },
      items: [
        {
          type: 'category',
          label: 'Preliminary',
          collapsed: true,
          items: [
            'introduction/how-to-read',
            'introduction/how-to-contribute',
            'introduction/how-to-write',
            'introduction/core-principles',
          ],
        },
        'project-management/index',
        chapter('Data Collection', '2_data-collection'),
        'data-governance/index',
        chapter('Annotation Design', '3_annotation-design'),
        chapterIndexed('Data Quality', 'data-quality/index', ['data-quality/equipment-setup']),
        chapter('Community', '10_community-collaboration'),
      ],
    },

    section('Text', 'sections/text', [
      chapterIndexed('Text Classification', 'text-classification/defining-text-classification-tasks', [
        'text-classification/collecting-and-preparing-data',
        'text-classification/annotation',
        {
          type: 'category',
          label: 'Example tasks',
          collapsed: true,
          items: [
            'text-classification/sentiment-analysis',
            'text-classification/emotion-analysis',
            'text-classification/hate-speech-analysis',
          ],
        },
      ]),
      chapterIndexed('Text Generation', 'text-generation/index', [
        'text-generation/generation',
        'text-generation/summarization',
        'text-generation/question-answering',
      ]),
      'machine-translation/index',
    ]),

    section('Speech', 'sections/speech', [
      'asr/index',
      'text-to-speech/index',
      'speech-to-speech-translation/index',
      'audio-understanding/index',
      'speech-emotion-recognition/index',
      'speaker-diarization/index',
    ]),

    section('Vision', 'sections/vision', [
      chapterIndexed('Image Data', 'image-data/index', [
        'image-data/classification',
        'image-data/object-detection',
        'image-data/segmentation',
      ]),
      chapterIndexed('Document AI', 'ocr-document-ai/index', [
        'ocr-document-ai/ocr',
        'ocr-document-ai/handwritten',
        'ocr-document-ai/layout',
      ]),
      chapterIndexed('Video', 'sign-language-video/index', [
        'sign-language-video/sign-language',
        'sign-language-video/gesture',
        'sign-language-video/video',
      ]),
    ]),

    section('Multimodal', 'sections/multimodal', [
      chapterIndexed('Image-Text', 'image-text/index', [
        'image-text/vqa',
        'image-text/captioning',
      ]),
      chapterIndexed('LLM-Assisted Data', 'llm-assisted-task/index', [
        'llm-assisted-task/equipment-setup',
      ]),
    ]),

    section('Lifecycle & Release', 'sections/lifecycle', [
      chapter('Evaluation', '8_model-building'),
      chapter('Documentation', '6_documentation'),
      chapter('Dataset Lifecycle', '9_dataset-lifecycle'),
    ]),

    {
      type: 'category',
      label: 'Appendix',
      collapsed: true,
      items: ['glossary', 'references'],
    },
  ],
};

export default sidebars;
