// Manual sidebar — the locked six-section structure.
// Existing multi-page chapters use `autogenerated`; task chapters and dropdowns
// are explicit. Files are not moved, so existing URLs are unchanged.

/** A collapsible chapter that pulls in all pages of an existing folder, plus
 * optional extra items (e.g. template refs) listed after them. */
const chapter = (label, dirName, extra = []) => ({
  type: 'category',
  label,
  collapsed: false,
  items: [{ type: 'autogenerated', dirName }, ...extra],
});

/** Templates live in docs/templates/ but belong, in the sidebar, to the chapter
 * that uses them, so Previous/Next runs straight from the chapter into its
 * template. `templateDoc` is that home placement. `templateRef` lists the same
 * page elsewhere (the Templates section, or a second chapter) without moving
 * or copying it; refs are skipped by Previous/Next. One file, one URL.
 * `where` makes each translation key unique: the i18n build fails when the
 * same page appears twice with the same label. */
const templateDoc = (id, label, where) => ({
  type: 'doc',
  id: `templates/${id}`,
  label: `Template: ${label}`,
  key: `template-${id}-${where}`,
});
const templateRef = (id, label, where) => ({
  type: 'ref',
  id: `templates/${id}`,
  label: label ? `Template: ${label}` : undefined,
  key: `template-${id}-${where}`,
});

/** A chapter with a landing page (the index) plus explicit child pages. */
const chapterIndexed = (label, indexId, items) => ({
  type: 'category',
  label,
  collapsed: false,
  link: { type: 'doc', id: indexId },
  items,
});

/** A section: a top-level group with an Overview landing page. Its direct
 * children are numbered as chapters (CSS counter in custom.css). Sections stay
 * open so hiding one never shifts the chapter numbers after it. */
const section = (label, overviewId, items) => ({
  type: 'category',
  label,
  className: 'sidebar-numbered',
  collapsible: false,
  link: { type: 'doc', id: overviewId },
  items,
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // Home page, shown as a bold "Welcome" entry like a Quarto book.
    { type: 'doc', id: 'introduction/index', label: 'Welcome', className: 'sidebar-welcome' },
    'introduction/introduction',
    {
      type: 'category',
      label: 'Foundations',
      className: 'sidebar-numbered',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Preliminary',
          collapsed: false,
          items: [
            'introduction/how-to-read',
            'introduction/how-to-contribute',
            'introduction/contributors',
            'introduction/how-to-write',
            'introduction/core-principles',
            'introduction/scope-and-strategy',
          ],
        },
        chapterIndexed('Before You Start', 'before-you-start/index', [
          'before-you-start/ner',
          'before-you-start/sentiment',
          'before-you-start/hate-speech',
          templateDoc('search-log', 'Dataset search log', 'before-you-start'),
        ]),
        chapterIndexed('Project Management', 'project-management/index', [
          templateDoc('project-charter', 'Project charter', 'project-management'),
        ]),
        'data-governance/index',
        chapter('Data Collection', '2_data-collection'),
        chapter('Annotation Design', '3_annotation-design', [templateDoc('annotation-guidelines', 'Annotation guidelines', 'annotation-design')]),
        chapterIndexed('Data Quality', 'data-quality/index', ['data-quality/equipment-setup']),
        chapter('Community', '10_community-collaboration'),
      ],
    },

    section('Text', 'sections/text', [
      chapterIndexed('Text Classification', 'text-classification/defining-text-classification-tasks', [
        'text-classification/collecting-and-preparing-data',
        'text-classification/annotation',
        {
          type: 'category',
          label: 'Example tasks',
          collapsed: false,
          items: [
            'text-classification/sentiment-analysis',
            'text-classification/emotion-analysis',
            'text-classification/hate-speech-analysis',
          ],
        },
      ]),
      chapterIndexed('Text Generation', 'text-generation/index', [
        'text-generation/generation',
        'text-generation/summarization',
        'text-generation/question-answering',
      ]),
      'machine-translation/index',
    ]),

    section('Speech', 'sections/speech', [
      'asr/index',
      'text-to-speech/index',
      'speech-to-speech-translation/index',
      'audio-understanding/index',
      'speech-emotion-recognition/index',
      'speaker-diarization/index',
    ]),

    section('Vision', 'sections/vision', [
      chapterIndexed('Image Data', 'image-data/index', [
        'image-data/classification',
        'image-data/object-detection',
        'image-data/segmentation',
      ]),
      chapterIndexed('Document AI', 'ocr-document-ai/index', [
        'ocr-document-ai/ocr',
        'ocr-document-ai/handwritten',
        'ocr-document-ai/layout',
      ]),
      chapterIndexed('Video', 'sign-language-video/index', [
        'sign-language-video/sign-language',
        'sign-language-video/gesture',
        'sign-language-video/video',
      ]),
    ]),

    section('Multimodal', 'sections/multimodal', [
      chapterIndexed('Image-Text', 'image-text/index', [
        'image-text/vqa',
        'image-text/captioning',
      ]),
      chapterIndexed('LLM-Assisted Data', 'llm-assisted-task/index', [
        'llm-assisted-task/equipment-setup',
      ]),
    ]),

    section('Lifecycle & Release', 'sections/lifecycle', [
      chapter('Evaluation', '8_model-building', [
        templateDoc('evaluation-script', 'Evaluation script', 'evaluation'),
        templateDoc('model-card', 'Model card', 'evaluation'),
      ]),
      chapter('Documentation', '6_documentation', [
        templateDoc('dataset-card', 'Dataset card', 'documentation'),
        templateRef('consent-form', 'Consent form', 'documentation'),
      ]),
      chapter('Dataset Lifecycle', '9_dataset-lifecycle'),
      chapterIndexed('Deployment', 'deployment/index', [
        'deployment/offline',
        'deployment/sms-ussd-whatsapp',
        'deployment/edge-devices',
        'deployment/multilingual-switching',
        'deployment/non-latin-scripts',
      ]),
      chapter('Cross-language transfer', 'cross-language-transfer'),
      chapter('Long-tail language onboarding', 'long-tail-language'),
      chapter('Legal, consent, and community IP', 'legal-consent', [templateDoc('consent-form', 'Consent form', 'legal-consent')]),
      chapter('Compute-poor training and evaluation', 'compute-poor'),
    ]),

    // Each template's home is its chapter (see templateDoc); listed here by ref.
    chapterIndexed('Templates', 'templates/index', [
      templateRef('search-log', null, 'templates'),
      templateRef('dataset-card', null, 'templates'),
      templateRef('evaluation-script', null, 'templates'),
      templateRef('consent-form', null, 'templates'),
      templateRef('annotation-guidelines', null, 'templates'),
      templateRef('project-charter', null, 'templates'),
      templateRef('model-card', null, 'templates'),
    ]),
    chapterIndexed('Case Studies', 'case-studies/index', [
      'case-studies/masakhaner',
      'case-studies/retrospective-template',
    ]),

    {
      type: 'category',
      label: 'Appendix',
      collapsed: false,
      items: ['glossary', 'references', 'tools-index'],
    },
  ],
};

export default sidebars;
