// Manual sidebar — the locked six-section structure.
// Existing multi-page chapters use `autogenerated`; task chapters and dropdowns
// are explicit. Files are not moved, so existing URLs are unchanged.

/** A collapsible chapter that pulls in all pages of an existing folder. */
const chapter = (label, dirName) => ({
  type: 'category',
  label,
  collapsed: false,
  items: [{ type: 'autogenerated', dirName }],
});

/** A chapter with a landing page (the index) plus explicit child pages. */
const chapterIndexed = (label, indexId, items) => ({
  type: 'category',
  label,
  collapsed: false,
  link: { type: 'doc', id: indexId },
  items,
});

/** A section: a top-level group with an Overview landing page. Its direct
 * children are numbered as chapters (CSS counter in custom.css). Sections stay
 * open so hiding one never shifts the chapter numbers after it. */
const section = (label, overviewId, items) => ({
  type: 'category',
  label,
  className: 'sidebar-numbered',
  collapsible: false,
  link: { type: 'doc', id: overviewId },
  items,
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // Home page, shown as a bold "Welcome" entry like a Quarto book.
    { type: 'doc', id: 'introduction/index', label: 'Welcome', className: 'sidebar-welcome' },
    {
      type: 'category',
      label: 'Preliminary',
      className: 'sidebar-chapter',
      collapsed: false,
      items: [
        'introduction/how-to-read',
        'introduction/how-to-contribute',
        'introduction/how-to-write',
        'introduction/core-principles',
        'introduction/scope-and-strategy',
      ],
    },
    // Foundation chapters sit at the top level, numbered via `sidebar-chapter`
    // like Preliminary above.
    ...[
      chapterIndexed('Before You Start', 'before-you-start/index', [
        'before-you-start/ner',
        'before-you-start/machine-translation',
        'before-you-start/asr',
        'before-you-start/sentiment',
        'before-you-start/hate-speech',
        'before-you-start/tts',
        'before-you-start/qa',
        'before-you-start/ocr',
      ]),
      { type: 'doc', id: 'project-management/index' },
      chapter('Data Collection', '2_data-collection'),
      { type: 'doc', id: 'data-governance/index' },
      chapter('Annotation Design', '3_annotation-design'),
      chapterIndexed('Data Quality', 'data-quality/index', ['data-quality/equipment-setup']),
      chapter('Community', '10_community-collaboration'),
    ].map((item) => ({ ...item, className: 'sidebar-chapter' })),

    section('Text', 'sections/text', [
      chapterIndexed('Text Classification', 'text-classification/defining-text-classification-tasks', [
        'text-classification/collecting-and-preparing-data',
        'text-classification/annotation',
        {
          type: 'category',
          label: 'Example tasks',
          collapsed: false,
          items: [
            'text-classification/sentiment-analysis',
            'text-classification/emotion-analysis',
            'text-classification/hate-speech-analysis',
          ],
        },
      ]),
      chapterIndexed('Text Generation', 'text-generation/index', [
        'text-generation/generation',
        'text-generation/summarization',
        'text-generation/question-answering',
      ]),
      'machine-translation/index',
    ]),

    section('Speech', 'sections/speech', [
      'asr/index',
      'text-to-speech/index',
      'speech-to-speech-translation/index',
      'audio-understanding/index',
      'speech-emotion-recognition/index',
      'speaker-diarization/index',
    ]),

    section('Vision', 'sections/vision', [
      chapterIndexed('Image Data', 'image-data/index', [
        'image-data/classification',
        'image-data/object-detection',
        'image-data/segmentation',
      ]),
      chapterIndexed('Document AI', 'ocr-document-ai/index', [
        'ocr-document-ai/ocr',
        'ocr-document-ai/handwritten',
        'ocr-document-ai/layout',
      ]),
      chapterIndexed('Video', 'sign-language-video/index', [
        'sign-language-video/sign-language',
        'sign-language-video/gesture',
        'sign-language-video/video',
      ]),
    ]),

    section('Multimodal', 'sections/multimodal', [
      chapterIndexed('Image-Text', 'image-text/index', [
        'image-text/vqa',
        'image-text/captioning',
      ]),
      chapterIndexed('LLM-Assisted Data', 'llm-assisted-task/index', [
        'llm-assisted-task/equipment-setup',
      ]),
    ]),

    section('Lifecycle & Release', 'sections/lifecycle', [
      chapter('Evaluation', '8_model-building'),
      chapter('Documentation', '6_documentation'),
      chapter('Dataset Lifecycle', '9_dataset-lifecycle'),
      chapterIndexed('Deployment', 'deployment/index', [
        'deployment/offline',
        'deployment/sms-ussd-whatsapp',
        'deployment/edge-devices',
        'deployment/multilingual-switching',
        'deployment/non-latin-scripts',
      ]),
      chapter('Cross-language transfer', 'cross-language-transfer'),
      chapter('Long-tail language onboarding', 'long-tail-language'),
      chapter('Legal, consent, and community IP', 'legal-consent'),
      chapter('Compute-poor training and evaluation', 'compute-poor'),
      chapter('Finding current resources', 'finding-resources'),
    ]),

    chapterIndexed('Templates', 'templates/index', [
      'templates/dataset-card',
      'templates/evaluation-script',
      'templates/consent-form',
      'templates/annotation-guidelines',
      'templates/project-charter',
      'templates/model-card',
    ]),
    chapterIndexed('Case Studies', 'case-studies/index', [
      'case-studies/masakhaner',
      'case-studies/retrospective-template',
    ]),

    {
      type: 'category',
      label: 'Appendix',
      collapsed: false,
      items: ['glossary', 'references'],
    },
  ],
};

export default sidebars;
